(function(g){g.fn.drag=function(b,a,c){var e="string"==typeof b?b:"",f=g.isFunction(b)?b:g.isFunction(a)?a:null;0!==e.indexOf("drag")&&(e="drag"+e);c=(b==f?a:c)||{};return f?this.bind(e,c,f):this.trigger(e)};var i=g.event,f=i.special,c=f.drag={defaults:{which:1,distance:0,not:":input",handle:null,relative:!1,drop:!0,click:!1},datakey:"dragdata",livekey:"livedrag",add:function(b){var a=g.data(this,c.datakey),d=b.data||{};a.related+=1;!a.live&&b.selector&&(a.live=!0,i.add(this,"draginit."+c.livekey,
c.delegate));g.each(c.defaults,function(b){d[b]!==void 0&&(a[b]=d[b])})},remove:function(){g.data(this,c.datakey).related-=1},setup:function(){if(!g.data(this,c.datakey)){var b=g.extend({related:0},c.defaults);g.data(this,c.datakey,b);i.add(this,"mousedown",c.init,b);this.attachEvent&&this.attachEvent("ondragstart",c.dontstart)}},teardown:function(){g.data(this,c.datakey).related||(g.removeData(this,c.datakey),i.remove(this,"mousedown",c.init),i.remove(this,"draginit",c.delegate),c.textselect(!0),
this.detachEvent&&this.detachEvent("ondragstart",c.dontstart))},init:function(b){var a=b.data,d;if(!(0<a.which&&b.which!=a.which)&&!g(b.target).is(a.not)&&(!a.handle||g(b.target).closest(a.handle,b.currentTarget).length))if(a.propagates=1,a.interactions=[c.interaction(this,a)],a.target=b.target,a.pageX=b.pageX,a.pageY=b.pageY,a.dragging=null,d=c.hijack(b,"draginit",a),a.propagates){if((d=c.flatten(d))&&d.length)a.interactions=[],g.each(d,function(){a.interactions.push(c.interaction(this,a))});a.propagates=
a.interactions.length;!1!==a.drop&&f.drop&&f.drop.handler(b,a);c.textselect(!1);i.add(document,"mousemove mouseup",c.handler,a);return!1}},interaction:function(b,a){return{drag:b,callback:new c.callback,droppable:[],offset:g(b)[a.relative?"position":"offset"]()||{top:0,left:0}}},handler:function(b){var a=b.data;switch(b.type){case !a.dragging&&"mousemove":if(Math.pow(b.pageX-a.pageX,2)+Math.pow(b.pageY-a.pageY,2)<Math.pow(a.distance,2))break;b.target=a.target;c.hijack(b,"dragstart",a);a.propagates&&
(a.dragging=!0);case "mousemove":if(a.dragging){c.hijack(b,"drag",a);if(a.propagates){!1!==a.drop&&f.drop&&f.drop.handler(b,a);break}b.type="mouseup"}case "mouseup":if(i.remove(document,"mousemove mouseup",c.handler),a.dragging&&(!1!==a.drop&&f.drop&&f.drop.handler(b,a),c.hijack(b,"dragend",a)),c.textselect(!0),!1===a.click&&a.dragging)jQuery.event.triggered=!0,setTimeout(function(){jQuery.event.triggered=false},20),a.dragging=!1}},delegate:function(b){var a=[],d,e=g.data(this,"events")||{};g.each(e.live||
[],function(e,f){if(0===f.preType.indexOf("drag")&&(d=g(b.target).closest(f.selector,b.currentTarget)[0]))i.add(d,f.origType+"."+c.livekey,f.origHandler,f.data),0>g.inArray(d,a)&&a.push(d)});return!a.length?!1:g(a).bind("dragend."+c.livekey,function(){i.remove(this,"."+c.livekey)})},hijack:function(b,a,d,e,f){if(d){var n=b.originalEvent,o=b.type,l=a.indexOf("drop")?"drag":"drop",j,m=e||0,h,k,e=!isNaN(e)?e:d.interactions.length;b.type=a;b.originalEvent=null;d.results=[];do if((h=d.interactions[m])&&
!("dragend"!==a&&h.cancelled))k=c.properties(b,d,h),h.results=[],g(f||h[l]||d.droppable).each(function(e,f){j=(k.target=f)?i.handle.call(f,b,k):null;!1===j?("drag"==l&&(h.cancelled=!0,d.propagates-=1),"drop"==a&&(h[l][e]=null)):"dropinit"==a&&h.droppable.push(c.element(j)||f);"dragstart"==a&&(h.proxy=g(c.element(j)||h.drag)[0]);h.results.push(j);delete b.result;if("dropinit"!==a)return j}),d.results[m]=c.flatten(h.results),"dropinit"==a&&(h.droppable=c.flatten(h.droppable)),"dragstart"==a&&!h.cancelled&&
k.update();while(++m<e);b.type=o;b.originalEvent=n;return c.flatten(d.results)}},properties:function(b,a,d){var e=d.callback;e.drag=d.drag;e.proxy=d.proxy||d.drag;e.startX=a.pageX;e.startY=a.pageY;e.deltaX=b.pageX-a.pageX;e.deltaY=b.pageY-a.pageY;e.originalX=d.offset.left;e.originalY=d.offset.top;e.offsetX=b.pageX-(a.pageX-e.originalX);e.offsetY=b.pageY-(a.pageY-e.originalY);e.drop=c.flatten((d.drop||[]).slice());e.available=c.flatten((d.droppable||[]).slice());return e},element:function(b){if(b&&
(b.jquery||1==b.nodeType))return b},flatten:function(b){return g.map(b,function(a){return a&&a.jquery?g.makeArray(a):a&&a.length?c.flatten(a):a})},textselect:function(b){g(document)[b?"unbind":"bind"]("selectstart",c.dontstart).attr("unselectable",b?"off":"on").css("MozUserSelect",b?"":"none")},dontstart:function(){return!1},callback:function(){}};c.callback.prototype={update:function(){f.drop&&this.available.length&&g.each(this.available,function(b){f.drop.locate(this,b)})}};f.draginit=f.dragstart=
f.dragend=c})(jQuery);